[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm_parser = { path = "../wasm_parser" }
# inkwell = { version = "0.4.0", features = ["llvm18-0"] }
