//! Wasmicon HAL のゲスト向け extern 宣言と enum（ゲスト側）。
//!
//! @generated by `cargo run -p wasmicon-gen` — 手で編集しない。
//! 生成元: wit/（wasmicon:hal@0.1.0）。lowering 規則: docs/abi-spec.md

pub mod types {
    /// HAL 共通のエラーコード。
    /// Wasmicon ABI では、result<T, error-code> を返す関数は
    /// 単一の i32 を返し、0 = 成功、n > 0 = (discriminant + 1) を意味する。
    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum ErrorCode {
        /// 引数が不正（範囲外の pin 番号、長さ 0 の転送など）
        InvalidArgument = 0,
        /// ハンドルが無効、または既に drop されている
        InvalidHandle = 1,
        /// 対象のペリフェラル・ピンが既に使用中
        Busy = 2,
        /// タイムアウト
        Timeout = 3,
        /// I2C: デバイスから NACK が返った
        Nack = 4,
        /// バスエラーなど、その他の I/O エラー
        Io = 5,
        /// このプラットフォームではサポートされない操作・設定
        Unsupported = 6,
        /// ホスト側のリソース不足（ハンドル上限など）
        OutOfMemory = 7,
    }

    impl ErrorCode {
        /// ケース数。
        pub const COUNT: u32 = 8;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::InvalidArgument),
                1 => Some(Self::InvalidHandle),
                2 => Some(Self::Busy),
                3 => Some(Self::Timeout),
                4 => Some(Self::Nack),
                5 => Some(Self::Io),
                6 => Some(Self::Unsupported),
                7 => Some(Self::OutOfMemory),
                _ => None,
            }
        }

        /// ホストが返すステータス値。discriminant + 1（abi-spec §4.4）。
        #[must_use]
        pub const fn status(self) -> u32 {
            self as u32 + 1
        }

        /// ステータス値から復元する。0（成功）と範囲外は `None`。
        #[must_use]
        pub const fn from_status(status: u32) -> Option<Self> {
            if status == 0 {
                return None;
            }
            Self::from_u32(status - 1)
        }
    }
}

/// 汎用デジタル入出力。
pub mod gpio {
    #[link(wasm_import_module = "wasmicon:hal/gpio@0.1.0")]
    unsafe extern "C" {
        /// ピンを確保しモードを設定する。既に確保済みなら busy。
        #[link_name = "[static]pin.open"]
        pub fn pin_open(index: u32, mode: u32, out: *mut u32) -> u32;

        /// モードを変更する。
        #[link_name = "[method]pin.set-mode"]
        pub fn pin_set_mode(this: u32, mode: u32) -> u32;

        /// 現在の入力レベルを読む。出力モードでも読める（出力値が返る）。
        #[link_name = "[method]pin.read"]
        pub fn pin_read(this: u32, out: *mut u32) -> u32;

        /// 出力レベルを設定する。入力モードなら invalid-argument。
        #[link_name = "[method]pin.write"]
        pub fn pin_write(this: u32, level: u32) -> u32;

        /// 出力レベルを反転する。
        #[link_name = "[method]pin.toggle"]
        pub fn pin_toggle(this: u32) -> u32;

        /// pin のハンドルを解放する。無効なハンドルは無視される（abi-spec §5.2）。
        #[link_name = "[resource-drop]pin"]
        pub fn pin_drop(this: u32);
    }

    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Level {
        Low = 0,
        High = 1,
    }

    impl Level {
        /// ケース数。
        pub const COUNT: u32 = 2;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Low),
                1 => Some(Self::High),
                _ => None,
            }
        }
    }

    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum PinMode {
        /// 入力（プル無し）
        Input = 0,
        /// 入力（プルアップ）
        InputPullUp = 1,
        /// 入力（プルダウン）
        InputPullDown = 2,
        /// プッシュプル出力
        Output = 3,
        /// オープンドレイン出力
        OutputOpenDrain = 4,
    }

    impl PinMode {
        /// ケース数。
        pub const COUNT: u32 = 5;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Input),
                1 => Some(Self::InputPullUp),
                2 => Some(Self::InputPullDown),
                3 => Some(Self::Output),
                4 => Some(Self::OutputOpenDrain),
                _ => None,
            }
        }
    }
}

/// I2C マスター。
pub mod i2c {
    #[link(wasm_import_module = "wasmicon:hal/i2c@0.1.0")]
    unsafe extern "C" {
        /// バスを初期化して確保する。
        #[link_name = "[static]bus.open"]
        pub fn bus_open(index: u32, speed: u32, out: *mut u32) -> u32;

        /// 7bit アドレス address のデバイスに data を書く（START ... STOP）。
        #[link_name = "[method]bus.write"]
        pub fn bus_write(this: u32, address: u32, data_ptr: *const u8, data_len: u32) -> u32;

        /// 7bit アドレス address のデバイスから len バイト読む（START ... STOP）。
        /// Wasmicon ABI では戻りの list<u8> は呼び出し側が用意したバッファに書き込まれる。
        #[link_name = "[method]bus.read"]
        pub fn bus_read(
            this: u32,
            address: u32,
            len: u32,
            buf: *mut u8,
            cap: u32,
            len_out: *mut u32,
        ) -> u32;

        /// data を書いた後、Repeated START で len バイト読む（STOP は最後のみ）。
        /// レジスタ読み出しの定型パターン。
        #[link_name = "[method]bus.write-read"]
        pub fn bus_write_read(
            this: u32,
            address: u32,
            data_ptr: *const u8,
            data_len: u32,
            len: u32,
            buf: *mut u8,
            cap: u32,
            len_out: *mut u32,
        ) -> u32;

        /// bus のハンドルを解放する。無効なハンドルは無視される（abi-spec §5.2）。
        #[link_name = "[resource-drop]bus"]
        pub fn bus_drop(this: u32);
    }

    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Speed {
        /// 100 kHz
        Standard = 0,
        /// 400 kHz
        Fast = 1,
        /// 1 MHz
        FastPlus = 2,
    }

    impl Speed {
        /// ケース数。
        pub const COUNT: u32 = 3;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Standard),
                1 => Some(Self::Fast),
                2 => Some(Self::FastPlus),
                _ => None,
            }
        }
    }
}

/// SPI マスター。
/// チップセレクト (CS) はこのインターフェースでは扱わない。
/// ゲストが gpio で CS/DC ピンを直接制御する（ILI9341 のような DC 付きデバイスに合わせた設計）。
/// ビット順は MSB first 固定、ワード幅は 8bit 固定。
pub mod spi {
    #[link(wasm_import_module = "wasmicon:hal/spi@0.1.0")]
    unsafe extern "C" {
        /// バスを初期化して確保する。frequency-hz はホストが対応できる最も近い値に丸められる。
        #[link_name = "[static]bus.open"]
        pub fn bus_open(index: u32, frequency_hz: u32, mode: u32, out: *mut u32) -> u32;

        /// data を送信する。受信データは捨てる。ディスプレイ描画のホットパス。
        #[link_name = "[method]bus.write"]
        pub fn bus_write(this: u32, data_ptr: *const u8, data_len: u32) -> u32;

        /// 全二重転送。data を送信し、同じ長さの受信データを返す。
        /// Wasmicon ABI では戻りの list<u8> は呼び出し側が用意したバッファに書き込まれる。
        #[link_name = "[method]bus.transfer"]
        pub fn bus_transfer(
            this: u32,
            data_ptr: *const u8,
            data_len: u32,
            buf: *mut u8,
            cap: u32,
            len_out: *mut u32,
        ) -> u32;

        /// bus のハンドルを解放する。無効なハンドルは無視される（abi-spec §5.2）。
        #[link_name = "[resource-drop]bus"]
        pub fn bus_drop(this: u32);
    }

    /// CPOL/CPHA の組み合わせ。
    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Mode {
        /// CPOL=0, CPHA=0
        Mode0 = 0,
        /// CPOL=0, CPHA=1
        Mode1 = 1,
        /// CPOL=1, CPHA=0
        Mode2 = 2,
        /// CPOL=1, CPHA=1
        Mode3 = 3,
    }

    impl Mode {
        /// ケース数。
        pub const COUNT: u32 = 4;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Mode0),
                1 => Some(Self::Mode1),
                2 => Some(Self::Mode2),
                3 => Some(Self::Mode3),
                _ => None,
            }
        }
    }
}

/// 時間。
pub mod time {
    #[link(wasm_import_module = "wasmicon:hal/time@0.1.0")]
    unsafe extern "C" {
        /// 起動からの単調増加マイクロ秒。ラップアラウンドは考慮しなくてよい（u64）。
        #[link_name = "now-us"]
        pub fn now_us() -> u64;

        /// ms ミリ秒ブロッキング待機。
        #[link_name = "sleep-ms"]
        pub fn sleep_ms(ms: u32);

        /// us マイクロ秒ブロッキング待機。ホストの分解能に依存する。
        #[link_name = "sleep-us"]
        pub fn sleep_us(us: u32);
    }
}

/// デバッグ出力。ホストは通常シリアルコンソールへ出力する。
pub mod log {
    #[link(wasm_import_module = "wasmicon:hal/log@0.1.0")]
    unsafe extern "C" {
        /// message は UTF-8。改行はホストが付加する。
        #[link_name = "log"]
        pub fn log(level: u32, message_ptr: *const u8, message_len: u32);
    }

    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Level {
        Error = 0,
        Warn = 1,
        Info = 2,
        Debug = 3,
    }

    impl Level {
        /// ケース数。
        pub const COUNT: u32 = 4;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Error),
                1 => Some(Self::Warn),
                2 => Some(Self::Info),
                3 => Some(Self::Debug),
                _ => None,
            }
        }
    }
}

/// ボード固有のピン割り当てを役割名で引く。
/// 同一の Wasm バイナリを ESP32-S3 と RP2040 の両方で動かすために必要
/// （HANDOFF §3 #2、abi-spec §8）。
pub mod board {
    #[link(wasm_import_module = "wasmicon:hal/board@0.1.0")]
    unsafe extern "C" {
        /// 役割名から GPIO 番号を引く。
        /// そのボードに割り当てが無ければ unsupported を返す。
        ///
        /// 役割名は小文字の kebab-case。v0.1 で定めるもの:
        /// - `led`      オンボード LED
        /// - `lcd-cs`   ILI9341 のチップセレクト
        /// - `lcd-dc`   ILI9341 のデータ/コマンド切り替え
        /// - `lcd-rst`  ILI9341 のリセット
        #[link_name = "pin-by-role"]
        pub fn pin_by_role(role_ptr: *const u8, role_len: u32, out: *mut u32) -> u32;
    }
}
