//! 3 つの生成物を文字列として組み立てる。
//!
//! - `runtime/src/generated.rs` — import 表とエラーコード（ホスト側）
//! - `bindings/rust/src/generated.rs` — extern 宣言と enum（ゲスト側）
//! - `bindings/assemblyscript/assembly/generated.ts` — 同上

use std::fmt::Write as _;

use crate::model::{EnumDef, FlagsDef, Hal, Import, Ret};

/// 生成物の先頭に置く注意書き。
fn banner(hal: &Hal, comment: &str) -> String {
    format!(
        "{c} @generated by `cargo run -p wasmicon-gen` — 手で編集しない。\n\
         {c} 生成元: wit/（{pkg}）。lowering 規則: docs/abi-spec.md\n",
        c = comment,
        pkg = hal.package
    )
}

fn rust_doc(out: &mut String, indent: &str, docs: &[String]) {
    for line in docs {
        if line.is_empty() {
            let _ = writeln!(out, "{indent}///");
        } else {
            let _ = writeln!(out, "{indent}/// {line}");
        }
    }
}

/// JSDoc ブロックを途中で終わらせないようにする。WIT の `///` に `*/` が
/// 入ると生成した .ts が壊れるが、それをコンパイルするのは Phase 3 なので
/// ここで防いでおかないと壊れた生成物がそのままコミットされる。
fn ts_escape(line: &str) -> String {
    line.replace("*/", "*\\/")
}

fn ts_doc(out: &mut String, indent: &str, docs: &[String]) {
    if docs.is_empty() {
        return;
    }
    let _ = writeln!(out, "{indent}/**");
    for line in docs {
        let _ = writeln!(out, "{indent} * {}", ts_escape(line));
    }
    let _ = writeln!(out, "{indent} */");
}

/// Rust の予約語を避ける。`self` だけは `this` に読み替える（abi-spec 付録 A）。
fn rust_param_name(name: &str) -> String {
    match name {
        "self" => "this".to_string(),
        other => crate::lower::snake(other),
    }
}

/// AssemblyScript の引数名は lowerCamel（abi-spec 付録 B）。
fn ts_param_name(name: &str) -> String {
    let mut parts = name.split(['-', '.']).filter(|p| !p.is_empty());
    let mut s = parts.next().unwrap_or_default().to_string();
    for p in parts {
        s.push_str(&crate::lower::pascal(p));
    }
    s
}

/// enum 本体（Rust）。`extra` に追加の impl 項目を書ける。
fn rust_enum(out: &mut String, indent: &str, e: &EnumDef, extra: &str) {
    rust_doc(out, indent, &e.docs);
    let _ = writeln!(out, "{indent}#[derive(Clone, Copy, PartialEq, Eq)]");
    let _ = writeln!(out, "{indent}#[repr(u32)]");
    let _ = writeln!(out, "{indent}pub enum {} {{", e.rust_name);
    for (i, c) in e.cases.iter().enumerate() {
        rust_doc(out, &format!("{indent}    "), &c.docs);
        let _ = writeln!(out, "{indent}    {} = {i},", c.ident);
    }
    let _ = writeln!(out, "{indent}}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "{indent}impl {} {{", e.rust_name);
    let _ = writeln!(out, "{indent}    /// ケース数。");
    let _ = writeln!(out, "{indent}    pub const COUNT: u32 = {};", e.cases.len());
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "{indent}    /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。"
    );
    let _ = writeln!(out, "{indent}    #[must_use]");
    let _ = writeln!(
        out,
        "{indent}    pub const fn from_u32(v: u32) -> Option<Self> {{"
    );
    let _ = writeln!(out, "{indent}        match v {{");
    for (i, c) in e.cases.iter().enumerate() {
        let _ = writeln!(out, "{indent}            {i} => Some(Self::{}),", c.ident);
    }
    let _ = writeln!(out, "{indent}            _ => None,");
    let _ = writeln!(out, "{indent}        }}");
    let _ = writeln!(out, "{indent}    }}");
    out.push_str(extra);
    let _ = writeln!(out, "{indent}}}");
}

/// flags を定数の集合として出す（abi-spec §4.1）。
fn rust_flags(out: &mut String, indent: &str, f: &FlagsDef) {
    rust_doc(out, indent, &f.docs);
    let _ = writeln!(out, "{indent}pub struct {};", f.rust_name);
    let _ = writeln!(out);
    let _ = writeln!(out, "{indent}impl {} {{", f.rust_name);
    for (i, b) in f.bits.iter().enumerate() {
        rust_doc(out, &format!("{indent}    "), &b.docs);
        let _ = writeln!(out, "{indent}    pub const {}: u32 = 1 << {i};", b.ident);
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "{indent}    /// 定義済みビットのマスク。これ以外が立っていたら invalid-argument。"
    );
    let _ = writeln!(
        out,
        "{indent}    pub const ALL: u32 = {:#x};",
        flags_mask(f)
    );
    let _ = writeln!(out, "{indent}}}");
}

fn flags_mask(f: &FlagsDef) -> u32 {
    if f.bits.len() >= 32 {
        u32::MAX
    } else {
        (1u32 << f.bits.len()) - 1
    }
}

fn error_code_extra(indent: &str) -> String {
    let mut s = String::new();
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "{indent}    /// ホストが返すステータス値。discriminant + 1（abi-spec §4.4）。"
    );
    let _ = writeln!(s, "{indent}    #[must_use]");
    let _ = writeln!(s, "{indent}    pub const fn status(self) -> u32 {{");
    let _ = writeln!(s, "{indent}        self as u32 + 1");
    let _ = writeln!(s, "{indent}    }}");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "{indent}    /// ステータス値から復元する。0（成功）と範囲外は `None`。"
    );
    let _ = writeln!(s, "{indent}    #[must_use]");
    let _ = writeln!(
        s,
        "{indent}    pub const fn from_status(status: u32) -> Option<Self> {{"
    );
    let _ = writeln!(s, "{indent}        if status == 0 {{");
    let _ = writeln!(s, "{indent}            return None;");
    let _ = writeln!(s, "{indent}        }}");
    let _ = writeln!(s, "{indent}        Self::from_u32(status - 1)");
    let _ = writeln!(s, "{indent}    }}");
    s
}

fn is_error_code(e: &EnumDef) -> bool {
    e.wit_name == "error-code"
}

// ---------------------------------------------------------------- runtime

/// `runtime/src/generated.rs`
pub fn runtime_rs(hal: &Hal) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Wasmicon HAL の import 表とエラーコード（ホスト側）。"
    );
    let _ = writeln!(out, "//!");
    for line in banner(hal, "//!").lines() {
        let _ = writeln!(out, "{line}");
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "/// HAL import 1 つの記述子。");
    let _ = writeln!(out, "pub struct ImportDesc {{");
    let _ = writeln!(out, "    /// import モジュール名（abi-spec §3.1）。");
    let _ = writeln!(out, "    pub module: &'static str,");
    let _ = writeln!(out, "    /// import フィールド名（abi-spec §3.2）。");
    let _ = writeln!(out, "    pub name: &'static str,");
    let _ = writeln!(
        out,
        "    /// シグネチャ。`params:results`、`i`=i32 `I`=i64 `f`=f32 `F`=f64。"
    );
    let _ = writeln!(out, "    pub sig: &'static str,");
    let _ = writeln!(out, "    /// ポート層がディスパッチに使うスロット。");
    let _ = writeln!(out, "    pub host_fn: HostFn,");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "/// ホスト関数のスロット。`IMPORTS` の要素と 1 対 1 に対応する。"
    );
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Eq)]");
    let _ = writeln!(out, "#[repr(u16)]");
    let _ = writeln!(out, "pub enum HostFn {{");
    for (iface, f) in hal.imports() {
        let _ = writeln!(out, "    /// `{}` の `{}`", iface.module, f.name);
        let _ = writeln!(out, "    {},", f.slot);
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    let n = hal.imports().count();
    let _ = writeln!(out, "impl HostFn {{");
    let _ = writeln!(out, "    /// `IMPORTS` の索引。");
    let _ = writeln!(out, "    #[must_use]");
    let _ = writeln!(out, "    pub const fn index(self) -> u16 {{");
    let _ = writeln!(out, "        self as u16");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out);
    let _ = writeln!(out, "    /// 索引から復元する。");
    let _ = writeln!(out, "    #[must_use]");
    let _ = writeln!(
        out,
        "    pub const fn from_index(i: u16) -> Option<Self> {{"
    );
    let _ = writeln!(out, "        match i {{");
    for (i, (_, f)) in hal.imports().enumerate() {
        let _ = writeln!(out, "            {i} => Some(Self::{}),", f.slot);
    }
    let _ = writeln!(out, "            _ => None,");
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "/// v0.1 の全 HAL import（abi-spec §7）。");
    let _ = writeln!(out, "pub static IMPORTS: [ImportDesc; {n}] = [");
    for (iface, f) in hal.imports() {
        let _ = writeln!(out, "    ImportDesc {{");
        let _ = writeln!(out, "        module: \"{}\",", iface.module);
        let _ = writeln!(out, "        name: \"{}\",", f.name);
        let _ = writeln!(out, "        sig: \"{}\",", f.sig());
        let _ = writeln!(out, "        host_fn: HostFn::{},", f.slot);
        let _ = writeln!(out, "    }},");
    }
    let _ = writeln!(out, "];");
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "/// module 名と import 名で解決する。`sig` の照合は呼び出し側が行う。"
    );
    let _ = writeln!(out, "#[must_use]");
    let _ = writeln!(
        out,
        "pub fn resolve(module: &str, name: &str) -> Option<&'static ImportDesc> {{"
    );
    let _ = writeln!(
        out,
        "    IMPORTS.iter().find(|d| d.module == module && d.name == name)"
    );
    let _ = writeln!(out, "}}");

    for iface in &hal.interfaces {
        if iface.enums.is_empty() && iface.flags.is_empty() {
            continue;
        }
        let _ = writeln!(out);
        rust_doc(&mut out, "", &iface.docs);
        let _ = writeln!(out, "pub mod {} {{", crate::lower::snake(&iface.name));
        for (i, e) in iface.enums.iter().enumerate() {
            if i > 0 {
                let _ = writeln!(out);
            }
            let extra = if is_error_code(e) {
                error_code_extra("    ")
            } else {
                String::new()
            };
            rust_enum(&mut out, "    ", e, &extra);
        }
        for (i, f) in iface.flags.iter().enumerate() {
            if i > 0 || !iface.enums.is_empty() {
                let _ = writeln!(out);
            }
            rust_flags(&mut out, "    ", f);
        }
        let _ = writeln!(out, "}}");
    }

    if let Some(iface) = hal.interfaces.iter().find(|i| i.name == "types")
        && iface.enums.iter().any(is_error_code)
    {
        let _ = writeln!(out);
        let _ = writeln!(out, "pub use self::types::ErrorCode;");
    }

    out
}

// ---------------------------------------------------------------- bindings/rust

/// `bindings/rust/src/generated.rs`
pub fn bindings_rs(hal: &Hal) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Wasmicon HAL のゲスト向け extern 宣言と enum（ゲスト側）。"
    );
    let _ = writeln!(out, "//!");
    for line in banner(hal, "//!").lines() {
        let _ = writeln!(out, "{line}");
    }

    for iface in &hal.interfaces {
        let _ = writeln!(out);
        rust_doc(&mut out, "", &iface.docs);
        let _ = writeln!(out, "pub mod {} {{", crate::lower::snake(&iface.name));

        if !iface.imports.is_empty() {
            let _ = writeln!(
                out,
                "    #[link(wasm_import_module = \"{}\")]",
                iface.module
            );
            let _ = writeln!(out, "    unsafe extern \"C\" {{");
            for (i, f) in iface.imports.iter().enumerate() {
                if i > 0 {
                    let _ = writeln!(out);
                }
                rust_doc(&mut out, "        ", &f.docs);
                let _ = writeln!(out, "        #[link_name = \"{}\"]", f.name);
                let args = f
                    .params
                    .iter()
                    .map(|p| format!("{}: {}", rust_param_name(&p.name), p.rust()))
                    .collect::<Vec<_>>()
                    .join(", ");
                let ret = f.ret.rust().map(|r| format!(" -> {r}")).unwrap_or_default();
                let _ = writeln!(out, "        pub fn {}({args}){ret};", f.rust_name);
            }
            let _ = writeln!(out, "    }}");
        }

        for (i, e) in iface.enums.iter().enumerate() {
            if !iface.imports.is_empty() || i > 0 {
                let _ = writeln!(out);
            }
            let extra = if is_error_code(e) {
                error_code_extra("    ")
            } else {
                String::new()
            };
            rust_enum(&mut out, "    ", e, &extra);
        }
        for f in &iface.flags {
            if !iface.imports.is_empty() || !iface.enums.is_empty() {
                let _ = writeln!(out);
            }
            rust_flags(&mut out, "    ", f);
        }
        let _ = writeln!(out, "}}");
    }

    out
}

// ---------------------------------------------------------------- bindings/assemblyscript

/// `bindings/assemblyscript/assembly/generated.ts`
pub fn bindings_ts(hal: &Hal) -> String {
    let mut out = String::new();
    out.push_str(&banner(hal, "//"));

    for iface in &hal.interfaces {
        let _ = writeln!(out);
        let _ = writeln!(out, "// ---- {} ----", iface.module);
        if !iface.docs.is_empty() {
            let _ = writeln!(out);
            ts_doc(&mut out, "", &iface.docs);
        }

        for e in &iface.enums {
            let _ = writeln!(out);
            ts_doc(&mut out, "", &e.docs);
            let _ = writeln!(out, "export enum {} {{", e.as_name);
            for (i, c) in e.cases.iter().enumerate() {
                ts_doc(&mut out, "  ", &c.docs);
                let _ = writeln!(out, "  {} = {i},", c.ident);
            }
            let _ = writeln!(out, "}}");
        }

        for fl in &iface.flags {
            let _ = writeln!(out);
            ts_doc(&mut out, "", &fl.docs);
            let _ = writeln!(out, "// abi-spec §4.1: 宣言順にビット 0 から割り当てる。");
            for (i, b) in fl.bits.iter().enumerate() {
                ts_doc(&mut out, "", &b.docs);
                let _ = writeln!(
                    out,
                    "export const {}{}: u32 = {:#x};",
                    fl.as_name,
                    b.ident,
                    1u32 << i
                );
            }
            let _ = writeln!(
                out,
                "/** 定義済みビットのマスク。これ以外が立っていたら invalid-argument。 */"
            );
            let _ = writeln!(
                out,
                "export const {}All: u32 = {:#x};",
                fl.as_name,
                flags_mask(fl)
            );
        }

        for f in &iface.imports {
            let _ = writeln!(out);
            ts_doc(&mut out, "", &f.docs);
            let _ = writeln!(out, "@external(\"{}\", \"{}\")", iface.module, f.name);
            let args = f
                .params
                .iter()
                .map(|p| format!("{}: {}", ts_param_name(&p.name), p.assemblyscript()))
                .collect::<Vec<_>>()
                .join(", ");
            let ret = ts_ret(f);
            let _ = writeln!(out, "export declare function {}({args}): {ret};", f.as_name);
        }
    }

    out
}

fn ts_ret(f: &Import) -> String {
    match &f.ret {
        Ret::None => "void".to_string(),
        Ret::Status => "u32".to_string(),
        Ret::Scalar(s) => s.assemblyscript().to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::ts_escape;

    #[test]
    fn ts_escape_does_not_close_the_jsdoc_block() {
        let escaped = ts_escape("これは */ を含む");
        assert!(!escaped.contains("*/"), "JSDoc が途中で閉じる: {escaped}");
        assert_eq!(escaped, "これは *\\/ を含む");
    }

    #[test]
    fn ts_escape_leaves_ordinary_text_alone() {
        assert_eq!(ts_escape("普通のコメント"), "普通のコメント");
    }
}
