//! Wasmicon HAL の import 表とエラーコード（ホスト側）。
//!
//! @generated by `cargo run -p wasmicon-gen` — 手で編集しない。
//! 生成元: wit/（wasmicon:hal@0.1.0）。lowering 規則: docs/abi-spec.md

/// HAL import 1 つの記述子。
pub struct ImportDesc {
    /// import モジュール名（abi-spec §3.1）。
    pub module: &'static str,
    /// import フィールド名（abi-spec §3.2）。
    pub name: &'static str,
    /// シグネチャ。`params:results`、`i`=i32 `I`=i64 `f`=f32 `F`=f64。
    pub sig: &'static str,
    /// ポート層がディスパッチに使うスロット。
    pub host_fn: HostFn,
}

/// ホスト関数のスロット。`IMPORTS` の要素と 1 対 1 に対応する。
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum HostFn {
    /// `wasmicon:hal/gpio@0.1.0` の `[static]pin.open`
    GpioPinOpen,
    /// `wasmicon:hal/gpio@0.1.0` の `[method]pin.set-mode`
    GpioPinSetMode,
    /// `wasmicon:hal/gpio@0.1.0` の `[method]pin.read`
    GpioPinRead,
    /// `wasmicon:hal/gpio@0.1.0` の `[method]pin.write`
    GpioPinWrite,
    /// `wasmicon:hal/gpio@0.1.0` の `[method]pin.toggle`
    GpioPinToggle,
    /// `wasmicon:hal/gpio@0.1.0` の `[resource-drop]pin`
    GpioPinDrop,
    /// `wasmicon:hal/i2c@0.1.0` の `[static]bus.open`
    I2cBusOpen,
    /// `wasmicon:hal/i2c@0.1.0` の `[method]bus.write`
    I2cBusWrite,
    /// `wasmicon:hal/i2c@0.1.0` の `[method]bus.read`
    I2cBusRead,
    /// `wasmicon:hal/i2c@0.1.0` の `[method]bus.write-read`
    I2cBusWriteRead,
    /// `wasmicon:hal/i2c@0.1.0` の `[resource-drop]bus`
    I2cBusDrop,
    /// `wasmicon:hal/spi@0.1.0` の `[static]bus.open`
    SpiBusOpen,
    /// `wasmicon:hal/spi@0.1.0` の `[method]bus.write`
    SpiBusWrite,
    /// `wasmicon:hal/spi@0.1.0` の `[method]bus.transfer`
    SpiBusTransfer,
    /// `wasmicon:hal/spi@0.1.0` の `[resource-drop]bus`
    SpiBusDrop,
    /// `wasmicon:hal/time@0.1.0` の `now-us`
    TimeNowUs,
    /// `wasmicon:hal/time@0.1.0` の `sleep-ms`
    TimeSleepMs,
    /// `wasmicon:hal/time@0.1.0` の `sleep-us`
    TimeSleepUs,
    /// `wasmicon:hal/log@0.1.0` の `log`
    LogLog,
}

impl HostFn {
    /// `IMPORTS` の索引。
    #[must_use]
    pub const fn index(self) -> u16 {
        self as u16
    }

    /// 索引から復元する。
    #[must_use]
    pub const fn from_index(i: u16) -> Option<Self> {
        match i {
            0 => Some(Self::GpioPinOpen),
            1 => Some(Self::GpioPinSetMode),
            2 => Some(Self::GpioPinRead),
            3 => Some(Self::GpioPinWrite),
            4 => Some(Self::GpioPinToggle),
            5 => Some(Self::GpioPinDrop),
            6 => Some(Self::I2cBusOpen),
            7 => Some(Self::I2cBusWrite),
            8 => Some(Self::I2cBusRead),
            9 => Some(Self::I2cBusWriteRead),
            10 => Some(Self::I2cBusDrop),
            11 => Some(Self::SpiBusOpen),
            12 => Some(Self::SpiBusWrite),
            13 => Some(Self::SpiBusTransfer),
            14 => Some(Self::SpiBusDrop),
            15 => Some(Self::TimeNowUs),
            16 => Some(Self::TimeSleepMs),
            17 => Some(Self::TimeSleepUs),
            18 => Some(Self::LogLog),
            _ => None,
        }
    }
}

/// v0.1 の全 HAL import（abi-spec §7）。
pub static IMPORTS: [ImportDesc; 19] = [
    ImportDesc {
        module: "wasmicon:hal/gpio@0.1.0",
        name: "[static]pin.open",
        sig: "iii:i",
        host_fn: HostFn::GpioPinOpen,
    },
    ImportDesc {
        module: "wasmicon:hal/gpio@0.1.0",
        name: "[method]pin.set-mode",
        sig: "ii:i",
        host_fn: HostFn::GpioPinSetMode,
    },
    ImportDesc {
        module: "wasmicon:hal/gpio@0.1.0",
        name: "[method]pin.read",
        sig: "ii:i",
        host_fn: HostFn::GpioPinRead,
    },
    ImportDesc {
        module: "wasmicon:hal/gpio@0.1.0",
        name: "[method]pin.write",
        sig: "ii:i",
        host_fn: HostFn::GpioPinWrite,
    },
    ImportDesc {
        module: "wasmicon:hal/gpio@0.1.0",
        name: "[method]pin.toggle",
        sig: "i:i",
        host_fn: HostFn::GpioPinToggle,
    },
    ImportDesc {
        module: "wasmicon:hal/gpio@0.1.0",
        name: "[resource-drop]pin",
        sig: "i:",
        host_fn: HostFn::GpioPinDrop,
    },
    ImportDesc {
        module: "wasmicon:hal/i2c@0.1.0",
        name: "[static]bus.open",
        sig: "iii:i",
        host_fn: HostFn::I2cBusOpen,
    },
    ImportDesc {
        module: "wasmicon:hal/i2c@0.1.0",
        name: "[method]bus.write",
        sig: "iiii:i",
        host_fn: HostFn::I2cBusWrite,
    },
    ImportDesc {
        module: "wasmicon:hal/i2c@0.1.0",
        name: "[method]bus.read",
        sig: "iiiiii:i",
        host_fn: HostFn::I2cBusRead,
    },
    ImportDesc {
        module: "wasmicon:hal/i2c@0.1.0",
        name: "[method]bus.write-read",
        sig: "iiiiiiii:i",
        host_fn: HostFn::I2cBusWriteRead,
    },
    ImportDesc {
        module: "wasmicon:hal/i2c@0.1.0",
        name: "[resource-drop]bus",
        sig: "i:",
        host_fn: HostFn::I2cBusDrop,
    },
    ImportDesc {
        module: "wasmicon:hal/spi@0.1.0",
        name: "[static]bus.open",
        sig: "iiii:i",
        host_fn: HostFn::SpiBusOpen,
    },
    ImportDesc {
        module: "wasmicon:hal/spi@0.1.0",
        name: "[method]bus.write",
        sig: "iii:i",
        host_fn: HostFn::SpiBusWrite,
    },
    ImportDesc {
        module: "wasmicon:hal/spi@0.1.0",
        name: "[method]bus.transfer",
        sig: "iiiiii:i",
        host_fn: HostFn::SpiBusTransfer,
    },
    ImportDesc {
        module: "wasmicon:hal/spi@0.1.0",
        name: "[resource-drop]bus",
        sig: "i:",
        host_fn: HostFn::SpiBusDrop,
    },
    ImportDesc {
        module: "wasmicon:hal/time@0.1.0",
        name: "now-us",
        sig: ":I",
        host_fn: HostFn::TimeNowUs,
    },
    ImportDesc {
        module: "wasmicon:hal/time@0.1.0",
        name: "sleep-ms",
        sig: "i:",
        host_fn: HostFn::TimeSleepMs,
    },
    ImportDesc {
        module: "wasmicon:hal/time@0.1.0",
        name: "sleep-us",
        sig: "i:",
        host_fn: HostFn::TimeSleepUs,
    },
    ImportDesc {
        module: "wasmicon:hal/log@0.1.0",
        name: "log",
        sig: "iii:",
        host_fn: HostFn::LogLog,
    },
];

/// module 名と import 名で解決する。`sig` の照合は呼び出し側が行う。
#[must_use]
pub fn resolve(module: &str, name: &str) -> Option<&'static ImportDesc> {
    IMPORTS
        .iter()
        .find(|d| d.module == module && d.name == name)
}

pub mod types {
    /// HAL 共通のエラーコード。
    /// Wasmicon ABI では、result<T, error-code> を返す関数は
    /// 単一の i32 を返し、0 = 成功、n > 0 = (discriminant + 1) を意味する。
    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum ErrorCode {
        /// 引数が不正（範囲外の pin 番号、長さ 0 の転送など）
        InvalidArgument = 0,
        /// ハンドルが無効、または既に drop されている
        InvalidHandle = 1,
        /// 対象のペリフェラル・ピンが既に使用中
        Busy = 2,
        /// タイムアウト
        Timeout = 3,
        /// I2C: デバイスから NACK が返った
        Nack = 4,
        /// バスエラーなど、その他の I/O エラー
        Io = 5,
        /// このプラットフォームではサポートされない操作・設定
        Unsupported = 6,
        /// ホスト側のリソース不足（ハンドル上限など）
        OutOfMemory = 7,
    }

    impl ErrorCode {
        /// ケース数。
        pub const COUNT: u32 = 8;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::InvalidArgument),
                1 => Some(Self::InvalidHandle),
                2 => Some(Self::Busy),
                3 => Some(Self::Timeout),
                4 => Some(Self::Nack),
                5 => Some(Self::Io),
                6 => Some(Self::Unsupported),
                7 => Some(Self::OutOfMemory),
                _ => None,
            }
        }

        /// ホストが返すステータス値。discriminant + 1（abi-spec §4.4）。
        #[must_use]
        pub const fn status(self) -> u32 {
            self as u32 + 1
        }

        /// ステータス値から復元する。0（成功）と範囲外は `None`。
        #[must_use]
        pub const fn from_status(status: u32) -> Option<Self> {
            if status == 0 {
                return None;
            }
            Self::from_u32(status - 1)
        }
    }
}

/// 汎用デジタル入出力。
pub mod gpio {
    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Level {
        Low = 0,
        High = 1,
    }

    impl Level {
        /// ケース数。
        pub const COUNT: u32 = 2;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Low),
                1 => Some(Self::High),
                _ => None,
            }
        }
    }

    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum PinMode {
        /// 入力（プル無し）
        Input = 0,
        /// 入力（プルアップ）
        InputPullUp = 1,
        /// 入力（プルダウン）
        InputPullDown = 2,
        /// プッシュプル出力
        Output = 3,
        /// オープンドレイン出力
        OutputOpenDrain = 4,
    }

    impl PinMode {
        /// ケース数。
        pub const COUNT: u32 = 5;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Input),
                1 => Some(Self::InputPullUp),
                2 => Some(Self::InputPullDown),
                3 => Some(Self::Output),
                4 => Some(Self::OutputOpenDrain),
                _ => None,
            }
        }
    }
}

/// I2C マスター。
pub mod i2c {
    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Speed {
        /// 100 kHz
        Standard = 0,
        /// 400 kHz
        Fast = 1,
        /// 1 MHz
        FastPlus = 2,
    }

    impl Speed {
        /// ケース数。
        pub const COUNT: u32 = 3;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Standard),
                1 => Some(Self::Fast),
                2 => Some(Self::FastPlus),
                _ => None,
            }
        }
    }
}

/// SPI マスター。
/// チップセレクト (CS) はこのインターフェースでは扱わない。
/// ゲストが gpio で CS/DC ピンを直接制御する（ILI9341 のような DC 付きデバイスに合わせた設計）。
/// ビット順は MSB first 固定、ワード幅は 8bit 固定。
pub mod spi {
    /// CPOL/CPHA の組み合わせ。
    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Mode {
        /// CPOL=0, CPHA=0
        Mode0 = 0,
        /// CPOL=0, CPHA=1
        Mode1 = 1,
        /// CPOL=1, CPHA=0
        Mode2 = 2,
        /// CPOL=1, CPHA=1
        Mode3 = 3,
    }

    impl Mode {
        /// ケース数。
        pub const COUNT: u32 = 4;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Mode0),
                1 => Some(Self::Mode1),
                2 => Some(Self::Mode2),
                3 => Some(Self::Mode3),
                _ => None,
            }
        }
    }
}

/// デバッグ出力。ホストは通常シリアルコンソールへ出力する。
pub mod log {
    #[derive(Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum Level {
        Error = 0,
        Warn = 1,
        Info = 2,
        Debug = 3,
    }

    impl Level {
        /// ケース数。
        pub const COUNT: u32 = 4;

        /// discriminant から復元する。範囲外なら `None`（abi-spec §4.1）。
        #[must_use]
        pub const fn from_u32(v: u32) -> Option<Self> {
            match v {
                0 => Some(Self::Error),
                1 => Some(Self::Warn),
                2 => Some(Self::Info),
                3 => Some(Self::Debug),
                _ => None,
            }
        }
    }
}

pub use self::types::ErrorCode;
