// @generated by `cargo run -p wasmicon-gen` — 手で編集しない。
// 生成元: wit/（wasmicon:hal@0.1.0）。lowering 規則: docs/abi-spec.md

// ---- wasmicon:hal/types@0.1.0 ----

/**
 * HAL 共通のエラーコード。
 * Wasmicon ABI では、result<T, error-code> を返す関数は
 * 単一の i32 を返し、0 = 成功、n > 0 = (discriminant + 1) を意味する。
 */
export enum ErrorCode {
  /**
   * 引数が不正（範囲外の pin 番号、長さ 0 の転送など）
   */
  InvalidArgument = 0,
  /**
   * ハンドルが無効、または既に drop されている
   */
  InvalidHandle = 1,
  /**
   * 対象のペリフェラル・ピンが既に使用中
   */
  Busy = 2,
  /**
   * タイムアウト
   */
  Timeout = 3,
  /**
   * I2C: デバイスから NACK が返った
   */
  Nack = 4,
  /**
   * バスエラーなど、その他の I/O エラー
   */
  Io = 5,
  /**
   * このプラットフォームではサポートされない操作・設定
   */
  Unsupported = 6,
  /**
   * ホスト側のリソース不足（ハンドル上限など）
   */
  OutOfMemory = 7,
}

// ---- wasmicon:hal/gpio@0.1.0 ----

/**
 * 汎用デジタル入出力。
 */

export enum GpioLevel {
  Low = 0,
  High = 1,
}

export enum GpioPinMode {
  /**
   * 入力（プル無し）
   */
  Input = 0,
  /**
   * 入力（プルアップ）
   */
  InputPullUp = 1,
  /**
   * 入力（プルダウン）
   */
  InputPullDown = 2,
  /**
   * プッシュプル出力
   */
  Output = 3,
  /**
   * オープンドレイン出力
   */
  OutputOpenDrain = 4,
}

/**
 * ピンを確保しモードを設定する。既に確保済みなら busy。
 */
@external("wasmicon:hal/gpio@0.1.0", "[static]pin.open")
export declare function gpio_pin_open(index: u32, mode: u32, out: usize): u32;

/**
 * モードを変更する。
 */
@external("wasmicon:hal/gpio@0.1.0", "[method]pin.set-mode")
export declare function gpio_pin_set_mode(self: u32, mode: u32): u32;

/**
 * 現在の入力レベルを読む。出力モードでも読める（出力値が返る）。
 */
@external("wasmicon:hal/gpio@0.1.0", "[method]pin.read")
export declare function gpio_pin_read(self: u32, out: usize): u32;

/**
 * 出力レベルを設定する。入力モードなら invalid-argument。
 */
@external("wasmicon:hal/gpio@0.1.0", "[method]pin.write")
export declare function gpio_pin_write(self: u32, level: u32): u32;

/**
 * 出力レベルを反転する。
 */
@external("wasmicon:hal/gpio@0.1.0", "[method]pin.toggle")
export declare function gpio_pin_toggle(self: u32): u32;

/**
 * pin のハンドルを解放する。無効なハンドルは無視される（abi-spec §5.2）。
 */
@external("wasmicon:hal/gpio@0.1.0", "[resource-drop]pin")
export declare function gpio_pin_drop(self: u32): void;

// ---- wasmicon:hal/i2c@0.1.0 ----

/**
 * I2C マスター。
 */

export enum I2cSpeed {
  /**
   * 100 kHz
   */
  Standard = 0,
  /**
   * 400 kHz
   */
  Fast = 1,
  /**
   * 1 MHz
   */
  FastPlus = 2,
}

/**
 * バスを初期化して確保する。
 */
@external("wasmicon:hal/i2c@0.1.0", "[static]bus.open")
export declare function i2c_bus_open(index: u32, speed: u32, out: usize): u32;

/**
 * 7bit アドレス address のデバイスに data を書く（START ... STOP）。
 */
@external("wasmicon:hal/i2c@0.1.0", "[method]bus.write")
export declare function i2c_bus_write(self: u32, address: u32, dataPtr: usize, dataLen: u32): u32;

/**
 * 7bit アドレス address のデバイスから len バイト読む（START ... STOP）。
 * Wasmicon ABI では戻りの list<u8> は呼び出し側が用意したバッファに書き込まれる。
 */
@external("wasmicon:hal/i2c@0.1.0", "[method]bus.read")
export declare function i2c_bus_read(self: u32, address: u32, len: u32, buf: usize, cap: u32, lenOut: usize): u32;

/**
 * data を書いた後、Repeated START で len バイト読む（STOP は最後のみ）。
 * レジスタ読み出しの定型パターン。
 */
@external("wasmicon:hal/i2c@0.1.0", "[method]bus.write-read")
export declare function i2c_bus_write_read(self: u32, address: u32, dataPtr: usize, dataLen: u32, len: u32, buf: usize, cap: u32, lenOut: usize): u32;

/**
 * bus のハンドルを解放する。無効なハンドルは無視される（abi-spec §5.2）。
 */
@external("wasmicon:hal/i2c@0.1.0", "[resource-drop]bus")
export declare function i2c_bus_drop(self: u32): void;

// ---- wasmicon:hal/spi@0.1.0 ----

/**
 * SPI マスター。
 * チップセレクト (CS) はこのインターフェースでは扱わない。
 * ゲストが gpio で CS/DC ピンを直接制御する（ILI9341 のような DC 付きデバイスに合わせた設計）。
 * ビット順は MSB first 固定、ワード幅は 8bit 固定。
 */

/**
 * CPOL/CPHA の組み合わせ。
 */
export enum SpiMode {
  /**
   * CPOL=0, CPHA=0
   */
  Mode0 = 0,
  /**
   * CPOL=0, CPHA=1
   */
  Mode1 = 1,
  /**
   * CPOL=1, CPHA=0
   */
  Mode2 = 2,
  /**
   * CPOL=1, CPHA=1
   */
  Mode3 = 3,
}

/**
 * バスを初期化して確保する。frequency-hz はホストが対応できる最も近い値に丸められる。
 */
@external("wasmicon:hal/spi@0.1.0", "[static]bus.open")
export declare function spi_bus_open(index: u32, frequencyHz: u32, mode: u32, out: usize): u32;

/**
 * data を送信する。受信データは捨てる。ディスプレイ描画のホットパス。
 */
@external("wasmicon:hal/spi@0.1.0", "[method]bus.write")
export declare function spi_bus_write(self: u32, dataPtr: usize, dataLen: u32): u32;

/**
 * 全二重転送。data を送信し、同じ長さの受信データを返す。
 * Wasmicon ABI では戻りの list<u8> は呼び出し側が用意したバッファに書き込まれる。
 */
@external("wasmicon:hal/spi@0.1.0", "[method]bus.transfer")
export declare function spi_bus_transfer(self: u32, dataPtr: usize, dataLen: u32, buf: usize, cap: u32, lenOut: usize): u32;

/**
 * bus のハンドルを解放する。無効なハンドルは無視される（abi-spec §5.2）。
 */
@external("wasmicon:hal/spi@0.1.0", "[resource-drop]bus")
export declare function spi_bus_drop(self: u32): void;

// ---- wasmicon:hal/time@0.1.0 ----

/**
 * 時間。
 */

/**
 * 起動からの単調増加マイクロ秒。ラップアラウンドは考慮しなくてよい（u64）。
 */
@external("wasmicon:hal/time@0.1.0", "now-us")
export declare function time_now_us(): u64;

/**
 * ms ミリ秒ブロッキング待機。
 */
@external("wasmicon:hal/time@0.1.0", "sleep-ms")
export declare function time_sleep_ms(ms: u32): void;

/**
 * us マイクロ秒ブロッキング待機。ホストの分解能に依存する。
 */
@external("wasmicon:hal/time@0.1.0", "sleep-us")
export declare function time_sleep_us(us: u32): void;

// ---- wasmicon:hal/log@0.1.0 ----

/**
 * デバッグ出力。ホストは通常シリアルコンソールへ出力する。
 */

export enum LogLevel {
  Error = 0,
  Warn = 1,
  Info = 2,
  Debug = 3,
}

/**
 * message は UTF-8。改行はホストが付加する。
 */
@external("wasmicon:hal/log@0.1.0", "log")
export declare function log_log(level: u32, messagePtr: usize, messageLen: u32): void;

// ---- wasmicon:hal/board@0.1.0 ----

/**
 * ボード固有のピン割り当てを役割名で引く。
 * 同一の Wasm バイナリを ESP32-S3 と RP2040 の両方で動かすために必要
 * （HANDOFF §3 #2、abi-spec §8）。
 */

/**
 * 役割名から GPIO 番号を引く。
 * そのボードに割り当てが無ければ unsupported を返す。
 * 
 * 役割名は小文字の kebab-case。v0.1 で定めるもの:
 * - `led`      オンボード LED
 * - `lcd-cs`   ILI9341 のチップセレクト
 * - `lcd-dc`   ILI9341 のデータ/コマンド切り替え
 * - `lcd-rst`  ILI9341 のリセット
 */
@external("wasmicon:hal/board@0.1.0", "pin-by-role")
export declare function board_pin_by_role(rolePtr: usize, roleLen: u32, out: usize): u32;
